name: Deploy MkDocs to GitHub Pages # Le nom du workflow, visible dans l'onglet "Actions" de ton dépôt

on:
  push:
    branches:
      - main
      - master # Le workflow se déclenche automatiquement à chaque push sur les branches "main" ou "master"

permissions:
  contents: read # Accorde l'accès en lecture au contenu du dépôt. C'est plus sécurisé que "write".
  pages: write # Autorise le workflow à déployer le site sur GitHub Pages.
  id-token: write # Permet au workflow de s'authentifier de manière sécurisée auprès des services de GitHub.

jobs:
  build_and_deploy: # Nom de la tâche principale de ce workflow
    runs-on: ubuntu-latest # Spécifie le système d'exploitation de la machine virtuelle où le job s'exécutera

    steps:
      - name: Checkout # Étape 1 : Récupérer le code du dépôt
        uses: actions/checkout@v4 # Utilise l'action officielle pour cloner ton dépôt

      - name: Setup Python # Étape 2 : Configurer l'environnement Python
        uses: actions/setup-python@v5 # Utilise l'action officielle pour installer Python
        with:
          python-version: 3.x # Spécifie la version de Python à utiliser (ici, la dernière version 3)
          cache: 'pip' # Active la mise en cache pour pip, ce qui accélère les installations ultérieures

      - name: Install MkDocs and dependencies # Étape 3 : Installer les outils nécessaires
        run: pip install -r requirements.txt # Installe les dépendances listées dans le fichier requirements.txt
          
      - name: Build MkDocs site # Étape 4 : Générer le site statique
        run: mkdocs build # Exécute la commande de "build" qui génère les fichiers HTML, CSS, etc., dans le dossier "site"

      - name: Setup Pages # Étape 5 : Configurer l'environnement de déploiement de GitHub Pages
        uses: actions/configure-pages@v5 # Prépare l'environnement pour l'upload d'artefacts

      - name: Upload artifact # Étape 6 : Télécharger l'artefact de déploiement
        uses: actions/upload-pages-artifact@v3 # Utilise l'action officielle pour télécharger le dossier "site"
        with:
          path: './site' # Spécifie le chemin du dossier à uploader (le dossier "site" que nous avons généré)

      - name: Deploy to GitHub Pages # Étape 7 : Déployer le site
        id: deployment
        uses: actions/deploy-pages@v4 # Utilise l'action officielle pour publier l'artefact sur GitHub Pages